GIT:
  - Commits
    - Nombres que puede tomar un commit
      - Branchname
      - HEAD
      - c82a22c39cbc32...
      - c82a22c
      - name^
      - name^^
      - name^2
      - name~10
      - name:path
      - name^{tree}
      - name1..name2
